### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by fafaraway** [phistoh/phisHideUI#1]
hide friendly player/pet/minion/guardian names when I'm inside raid dungeon, restore them when I'm get out.

love this addon, thanks for your hard work 👍

**Comment by phistoh** [comment]
Oh, I just saw that I never actually answered. Sorry!

I think, this feature does not fit to this specific addon (because phisHideUI is more concerned with the functionality of hiding the whole UI via the hotkey). Though I think your addon idea would not be that hard to implement.
